#!/bin/sh

PREFIX="/usr/local"
mkdir -p "${DESTDIR}${PREFIX}"
mkdir -p "${DESTDIR}${PREFIX}/bin"
mkdir -p "${DESTDIR}${PREFIX}/lib"

./configure --prefix="$PREFIX" \
						--target=arm-none-eabi \
						--libdir="${DESTDIR}${PREFIX}/lib/arm-none-eabi" \
						--enable-multilib \
						--enable-interwork \
						--with-gnu-as \
						--with-mmap \
						--with-gnu-ld \
						--without-zstd \
						--disable-nls \
						--enable-ld=default \
						--enable-lto \
						--enable-gdb \
						--enable-gold \
						--enable-plugins \
						--enable-deterministic-archives
make tooldir=/usr/local
make tooldir=/usr/local DESTDIR="$1" install
