#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-fuse-no-tests.patch

meson setup \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dlibportal=disabled \
    -Dgeoclue=disabled \
    -Dsystemd=disabled \
    . output

ninja -C output
ninja -C output install

rm -rf "$1/usr/lib/systemd"
