#!/bin/sh -e

export DESTDIR="$1"

mkdir -p build/release
cd build/release

meson setup ../.. --buildtype=release \
	--prefix=/usr	\
	-Denable-cairo=enabled	\
	-Dpng-backend=libpng	\
	-Dsvg-backend=none

ninja
ninja install
