#!/bin/sh -e

COMMIT_ID="63558dc60562f46f74eba5d15dc9b1672fdb5dab"

# setup the sources manually
unzip $COMMIT_ID.zip
cd TLP-$COMMIT_ID

# package build

export DESTDIR="$1"

export TLP_WITH_ELOGIND=0
export TLP_WITH_SYSTEMD=0

mkdir -p "$1/usr/share/man"

make install
make install-man

# Remove unnecessary stuff
rm -rf "$1/lib/elogind"
rm -rf "$1/usr/lib/NetworkManager"
rm -rf "$1/lib/systemd"
