#!/bin/sh -e

export DESTDIR="$1"

script=examples/turn_off_gpu.sh

mkdir -p $DESTDIR/usr/bin

make
make DESTDIR="$1" PREFIX=/usr install

chmod +x $script
cp $script $DESTDIR/usr/bin/turn_off_gpu -v
