#!/bin/sh -e

make extraclean
./autogen.sh

./configure  --prefix=/usr \
	     --enable-link-time-optimization \
	     --with-cairo \
	     --with-gnutls \
	     --with-imagemagick \
	     --with-modules \
	     --with-native-compilation \
	     --with-pgtk \
	     --with-jpeg \
	     --with-tiff \
	     --with-png \
	     --with-rsvg \
	     --with-webp \
	     --without-dbus \
	     --without-lcms2 \
	     --without-libsystemd \
	     --without-gif \
	     --without-gconf \
	     --without-gsettings \
	     --without-m17n-flt \
	     --without-selinux \
       --without-x \
	     --without-xft \
	     --without-xaw3d \
	     --without-xim \
	     --without-xdbe \

make all
make install
cp ./emacsc "$DESTDIR/usr/bin"
chmod +x "$DESTDIR/usr/bin/emacsc"
