#!/bin/sh -e

OUT="$DESTDIR/usr/share/fonts/TTF/cascadia-code"
OUTST="$DESTDIR/usr/share/fonts/TTF/cascadia-code/static"

VER="2111.01"
FILE="CascadiaCode-$VER.zip"

unzip $FILE
mkdir -p $OUTST
for ttf in ttf/*.ttf; do
    install -Dm644 "$ttf" "$OUT"
done

for ttf in ttf/static/*.ttf; do
    install -Dm 644 "$ttf" "$OUTST"
done
