#!/bin/sh -e

export DESTDIR="$1"
# Temporary hack to fix the compiler flags cuz configure script is retarded
export CFLAGS="$CFLAGS `pkg-config --cflags --libs ncurses`"

./configure 	--prefix=/usr \
		--without-guile
make
make DESTDIR="$1" install
